version : 2 

sources:
  - name: raw
    schema : gz_raw_data

    tables :
      - name : sales
        identifier : raw_gwz_sales
        
      - name : product
        identifier : raw_gz_product
            
      - name : ship
        identifier : raw_gz_ship
   