version : 2 

sources:
  - name: raw
    schema : gz_raw_data
    description : greenweez raw data source

    tables :
      - name : sales
        freshness:
          warn_after: {count : 90, period : day}
        loaded_at_field: "CAST(date_date as TIMESTAMP)"
        identifier : raw_gwz_sales
        description : sales of greenweez / we have one row per product_id found in each orders_id
       
        columns :
           - name : orders_id || '-' || pdt_id
             tests :
              - unique
              - not_null
             
              
                       
          
           - name : date_date
             description : the date of purchase
           - name : orders_id
             description : numéro d'identification des commandes
           - name : pdt_id
             description : numéro d'identification du produit
           - name : revenue 
             description : prix unitaire
           - name : quantity
             description : quantité vendue

      
        
      - name : product
        identifier : raw_gz_product
        description : tableau de prix des produits
        columns :
          - name :  products_id
            description : PK numéro d'identification des produits
            tests :
              - unique
              - not_null
             
            
          
                  
          - name : purchse_price
            description : prix d'acquisition
            
      - name : ship
        identifier : raw_gz_ship
        description : coûts des frais d'envoi par commande
        columns :
           - name :  orders_id
             description : numéro de commande
             tests :
              - unique
              - not_null
             
             
           - name : shipping_fee
             description : frais de livraison
           - name : shipping_fee_1
             description : frais de livraison doublon
           - name : logcost
             description : frais de logistique
           - name : ship_cost
             description : frais d'envoi
      
      - name : adwords
        identifier : raw_gz_adwords
        description : coûts et résultats de la campagne adwords
        columns :
          - name : date_date
            description : date
          - name : paid_source
            description : société chargée de la campagne
          - name : campaign_key
            description: clé de campagne
          - name : camPGN_name
            description: nom de campagne/ parfois doublon de clé de campagne
          - name: ads_cost
            description: coût de la campagne
          - name: impression
            description: nombre d'impression
          - name: click
            description: nombre de clics
      
      - name : bing
        identifier : raw_gz_bing
        description : coûts et résultats de la campagne bing
        columns :
          - name : date_date
            description : date
          - name : paid_source
            description : société chargée de la campagne
          - name : campaign_key
            description: clé de campagne
          - name : camPGN_name
            description: nom de campagne/ parfois doublon de clé de campagne
          - name: ads_cost
            description: coût de la campagne
          - name: impression
            description: nombre d'impression
          - name: click
            description: nombre de clics

      - name : criteo
        identifier: raw_gz_criteo
        description: coûts et résultats de la campagne criteo
        columns :
          - name : date_date
            description : date
          - name : paid_source
            description : société chargée de la campagne
          - name : campaign_key
            description: clé de campagne
          - name : camPGN_name
            description: nom de campagne/ parfois doublon de clé de campagne
          - name: ads_cost
            description: coût de la campagne
          - name: impression
            description: nombre d'impression
          - name: click
            description: nombre de clics

      - name : facebook
        identifier: raw_gz_facebook
        description: coûts et résultats de la campagne facebook 
        columns :
          - name : date_date
            description : date
          - name : paid_source
            description : société chargée de la campagne
          - name : campaign_key
            description: clé de campagne
          - name : camPGN_name
            description: nom de campagne/ parfois doublon de clé de campagne
          - name: ads_cost
            description: coût de la campagne
          - name: impression
            description: nombre d'impression
          - name: click
            description: nombre de clics
